### ISSUE TITLE
No support for /clanwarleagues/wars/{warTag}

### ISSUE THREAD

**Issue by jfbenckhuijsen** [CaptEmulation/clash-of-clans-api#12]
The API /clanwarleagues/wars/{warTag} is not supported by this library. Ill submit a pull-req to include this.

**Comment by jfbenckhuijsen** [comment]
See pull request #14 . Fixes a typo I thought I had committed.

**Comment by jfbenckhuijsen** [comment]
Are you able to release a fix version including #14 ?

**Comment by CaptEmulation** [comment]
My bad for the delay.  Published `clash-of-clans-api@0.6.1`
