### ISSUE TITLE
clash-of-clans-api help

### ISSUE THREAD

**Issue by TDcloud** [CaptEmulation/clash-of-clans-api#19]
Hello, friend, I saw your clash-of-clans-api project on github. I am also a player of clash of tribes and want to use your clash-of-clans-api but I don’t understand how to use it. For more detailed documentation, I am a player who is new to programming tribal conflicts, thank you. Looking forward to your reply.

**Comment by ionutale** [comment]
here is a tutorial i just made, for you my friend:
https://medium.com/@alexionutale/how-to-use-clash-of-clans-api-cd4fe7406576

**Comment by ionutale** [comment]
if you like it, find this image and press it as much as you can
thank you
<img width="75" alt="Schermata 2020-06-20 alle 07 43 53" src="https://user-images.githubusercontent.com/2562455/85193540-d4685780-b2c9-11ea-9086-6aec35a979bc.png">

**Comment by CaptEmulation** [comment]
Thanks
