### ISSUE TITLE
How should the front end call Nepal?

### ISSUE THREAD

**Issue by getr00t** [CaptEmulation/clash-of-clans-api#24]
Hello, I want to use node as an environment and use the api you provide to make an interface, but I read the tutorial and didn't understand it. How should my front end use this interface?

**Comment by VivekSharma1897** [comment]
> Hello, I want to use node as an environment and use the api you provide to make an interface, but I read the tutorial and didn't understand it. How should my front end use this interface?

You would need to make Node Backend
