### ISSUE TITLE
does this work?

### ISSUE THREAD

**Issue by Teamtyler2** [CaptEmulation/clash-of-clans-api#4]
hi my name is Classifed200,
i was wondering if this is acctually real idk how to do it

**Comment by CaptEmulation** [comment]
Yes, this project is used by myself and others.  It will help if you are already familiar with nodejs as this is a nodejs project.  If you are familiar with other ecosystems there are other choices out there.

**Comment by CaptEmulation** [comment]
Closing as this not a software issue and this is not the correct venue for these sort of questions

**Comment by Teamtyler2** [comment]
where can i write questions i have a lot of them idk how to make this work

**Comment by Teamtyler2** [comment]
@CaptEmulation

**Comment by CaptEmulation** [comment]
Please see https://github.com/CaptEmulation/clash-of-clans-api/blob/master/README.md

**Comment by Teamtyler2** [comment]
i installed it but idk what the other code is to go to or for etc

**Comment by CaptEmulation** [comment]
Please join: https://discord.gg/JZwve
