### ISSUE TITLE
Ip address

### ISSUE THREAD

**Issue by rikarsen** [CaptEmulation/clash-of-clans-api#5]
how to get my localhost ip address to create token?

**Comment by CaptEmulation** [comment]
ask google "What's my ip address" https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=what%27s%20my%20ip%20address

**Comment by rikarsen** [comment]
it says `GET https://api.clashofclans.com/v1/clans/%23UPC2UQ 403 (Forbidden)
localhost/:1 Fetch API cannot load https://api.clashofclans.com/v1/clans/%23UPC2UQ. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 403. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
bundle.js:17 RequestError {name: "RequestError", message: "TypeError: Failed to fetch", cause: TypeError: Failed to fetch, error: TypeError: Failed to fetch, options: Object…}`

**Comment by CaptEmulation** [comment]
@rikarsen very sorry that I missed your latest comment-- I have been travelling internationally and very busy.  I am trying to better understand your problem.  Can you create a _gist_ that demonstrates this issue?   I do not seem to be having this problem.

**Comment by CaptEmulation** [comment]
If you are attempting to run this code in a browser then it will not work because of the CORS issue.  You can use https://github.com/CaptEmulation/coc-api-proxy to create a CORS-less proxy to https://api.clashofclans.com.  If you are running in NodeJS there should be no CORS issue and it should _Just Work_(tm)
